version: '3'

services:
  backend:
    container_name: backend-service
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/postgres

  frontend:
    container_name: frontend-service
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"

  db:
    container_name: postgres-service
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
