# DjangoVueStarter

This is a starter project that combines Django (backend) and Vue.js (frontend) using Docker for easy setup and deployment.

## Prerequisites

- Docker
- Docker Compose

## Running the Application

1. **Clone the repository:**

   ```sh
   git clone https://github.com/yourusername/DjangoVueStarter.git
   cd DjangoVueStarter

2. **Build and start the Docker containers:**

  ```sh
   docker-compose up --build

3. **Access the application**

  - Backend (Django): Open your browser and go to http://localhost:8000
  - Frontend (Vue.js): Open your browser and go to http://localhost:8080